/* Van Beirs — content localisation: Dutch & French */
window.CONTENT.nl = {
  stat_brands:'Investeringsmerken', stat_target:'Portefeuilledoel', stat_irr:'Gem. doel-IRR', stat_years:'Jaar M&A',
  about_p1:"Van Beirs Ventures B.V. is de professionele vennootschap voor vermogensbeheer en financiële producten van de Van Beirs-groep, opererend onder Van Beirs Holding B.V.",
  about_p2:"De entiteit houdt toezicht op zes investeringsvehikels, structureert en geeft de financiële instrumenten van de groep uit, en beheert de integratie tussen kapitaalmarkten en de onderliggende merkenportefeuilles.",
  about_mandate:"De activiteiten van de groep zijn gericht op investeringskapitaal in luxe, technologie en vastgoed — en combinaties daarvan.",
  history_note:'Erfgoeddata weerspiegelen portefeuillemerken. Mijlpalen van de groep worden nog bevestigd.',
  histItems:[
    { y:'1840', h:'Charles Fontana & Cie', d:'Huis van haute joaillerie opgericht aan 10, Place Vendôme, Parijs — vandaag een erfgoedmaison binnen de portefeuille.' },
    { y:'1897', h:'MINERVA', d:'Belgisch ultraluxe automerk opgericht — de basis van het handgebouwde waterstof-SUV-programma van de groep.' },
    { y:'2026', h:'Investeerdersprogramma van de groep', d:'Van Beirs Ventures publiceert zijn Group Investor Overview en lanceert de financiële instrumenten van Fase I via de investeringsvehikels.' },
  ],
  instr_meta:'EU-prospectusverord. · FSMA',
  instrItems:[
    { h:'Onderhandse obligatie', items:['Collateral Debt Obligations — onderhandse plaatsing','9,0% p.j. coupon · driemaandelijkse betaling','Looptijd 5 jaar · aflossing ineens','Converteerbaar met aandelenrechten klasse B','Gewaarborgd door merk- en IP-activa van de groep'] },
    { h:'Openbare financiële instrumenten', items:['Euronext Brussel / pan-Europese obligaties','FSMA-gereguleerde prospectusnaleving','Openbare obligatie I — overbrugging jaar 4','Openbare obligatie II — groei jaar 5','Euro MTF · Beurs van Luxemburg'] },
    { h:'Getokeniseerde instrumenten', items:['Digital-native versies van alle producten','Op blockchain geregistreerd eigendom & overdracht','Gefractioneerde toegang, kleinere tickets','Coupon & conversie via smart contracts','EU-MiCA-conforme architectuur'] },
    { h:'VB Certus Capital SA', items:['Luxemburgse SICAV-RAIF · multi-strategie','Klassen A · M · B · R','AIFM-toezicht · Part II UCI-wet','Streefrendement: 10–15% IRR','Euronext Brussel-notering bij € 100M+ AUM'] },
  ],
  inv_meta:'Afgeschermd · per vehikel', inv_k1:'1e investering', inv_k2:'Exit 5 jaar', inv_tbc:'N.t.b.', inv_req:'Op aanvraag',
  portfolio:[
    { sc:'Energie-innovaties', desc:'Batterijopslag, PV-integratie, EV-laden & waterstofsystemen. Eigen HydraCell-kast.' },
    { sc:'Haute joaillerie', desc:'10, Place Vendôme. Minder dan 25 unieke stukken per jaar vanaf €1,5M.' },
    { sc:'Ultraluxe auto’s', desc:'Belgische H2 V12-hybride SUV. 100 stuks/jaar, handgebouwd in het Antwerpse atelier.' },
    { sc:'Soeverein AI-toestel', desc:'Belgische luxe AI-smartphone. Europees model, privacy op het toestel, geen cloudafhankelijkheid.' },
    { sc:'Field-to-fork', desc:'Directe field-to-fork-connectiviteit, traceertechnologie en duurzame marktinfrastructuur.' },
    { sc:'Defensie · drone', desc:'NAVO-tactische UAS. IMEC neuromorfe AI, grafeen-supercondensator. EDF 2026 · Belgisch Defensie.' },
    { sc:'FinTech · Canton Network', desc:'Institutioneel security-token-platform op het Canton Network — tokeniseert en verrekent de financiële instrumenten van de groep.' },
    { sc:'Branded residences', desc:'Ultraluxe branded residences die het merk MINERVA uitbreiden naar prime patrimoniumvastgoed.' },
    { sc:'Prime RE · Antwerpen', desc:'VB001 — herenhuis van 800m² in de Justitiestraat. Drie van vier eenheden voorondertekend. Klasse R via VB Certus Capital.' },
  ],
  pitch_eyebrow:'Voor bedrijven die financiering zoeken',
  pitch_company:'Bedrijfsinformatie', pitch_management:'Managementinformatie', pitch_documents:'Documenten', pitch_ask:'De vraag',
  f_company:'Bedrijfsnaam', f_website:'Website', f_country:'Land', f_sector:'Sector',
  f_contact:'Contactpersoon', f_role:'Functie', f_emailL:'E-mail', f_phone:'Telefoon',
  f_accounts:'Jaarrekeningen laatste 3 jaar', f_accounts_h:'PDF / XLSX — jaarcijfers', f_presentation:'Bedrijfspresentatie', f_presentation_h:'PDF — max. 10 slides',
  f_financing:'Benodigde financiering (€)', f_timeframe:'Tijdsbestek',
  tf_select:'Kies…', tf_now:'Onmiddellijk (< 3 maanden)', tf_3_6:'3–6 maanden', tf_6_12:'6–12 maanden', tf_exp:'Verkennend',
  consent_pre:'Ik geef toestemming om per e-mail gecontacteerd te worden over dit voorstel, in overeenstemming met het ', consent_post:'.',
  pitch_submit:'Voorstel indienen', pitch_redirect:'Terug naar de startpagina…', file_choose:'Bestand kiezen', file_replace:'Bestand vervangen',
  login_email_ph:'naam@instelling.com',
  ft_rights:'Alle rechten voorbehouden',
  langLabel:'Taal', legal_eyebrow:'Juridisch', legal_entityLine:'Van Beirs Holding B.V. · Antwerpen, België', legal_dp:'Juridisch & gegevensbescherming:', legal_updated:'Laatst bijgewerkt 2026.',
  privacySections:[
    { h:'1 · Verwerkingsverantwoordelijke', p:'Deze website wordt beheerd door Van Beirs Holding B.V. (Antwerpen, België), die optreedt als verwerkingsverantwoordelijke voor de via deze site verwerkte persoonsgegevens.' },
    { h:'2 · Gegevens die wij verwerken', p:'Door u verstrekte informatie (bv. naam, institutioneel e-mailadres, berichten), authenticatiegegevens voor de investeerderslogin, en technische gegevens zoals IP-adres en browsertype, verzameld via strikt noodzakelijke en optionele cookies.' },
    { h:'3 · Doeleinden & rechtsgrond', p:'Om de site en het investeerdersgedeelte te exploiteren, vragen en voorstellen te beantwoorden, te voldoen aan wettelijke en reglementaire verplichtingen, en — met uw toestemming — het sitegebruik te begrijpen. De verwerking steunt op toestemming, gerechtvaardigd belang en wettelijke verplichting onder de AVG (Verordening (EU) 2016/679).' },
    { h:'4 · Cookies', p:'Strikt noodzakelijke cookies houden de site werkend en bewaren uw taalkeuze. Optionele analysecookies worden pas na toestemming geplaatst en kunnen op elk moment worden ingetrokken via “Cookie-instellingen”.' },
    { h:'5 · Bewaring & ontvangers', p:'Gegevens worden niet langer bewaard dan nodig voor bovenstaande doeleinden of wettelijk vereist, en uitsluitend gedeeld met dienstverleners en adviseurs gebonden door vertrouwelijkheid.' },
    { h:'6 · Uw rechten', p:'U kunt verzoeken om inzage, rectificatie, wissing, beperking, overdraagbaarheid of bezwaar maken tegen de verwerking, en een klacht indienen bij de Belgische Gegevensbeschermingsautoriteit.' },
  ],
  termsSections:[
    { h:'1 · Geen aanbod of werving', p:'De informatie op deze website wordt uitsluitend ter algemene informatie verstrekt en vormt geen aanbod, werving of aanbeveling om financiële instrumenten te onderschrijven, te kopen of te verkopen in enig rechtsgebied.' },
    { h:'2 · Vertrouwelijkheid', p:'Materiaal toegankelijk via het investeerdersgedeelte is vertrouwelijk en uitsluitend bestemd voor gemachtigde ontvangers. Het mag niet worden gereproduceerd of verspreid zonder voorafgaande schriftelijke toestemming.' },
    { h:'3 · Toekomstgerichte verklaringen', p:'Doelstellingen, prognoses, IRR- of multiple-cijfers zijn illustratief, onderhevig aan aanzienlijk risico en vormen geen voorspelling of garantie van toekomstige prestaties. Resultaten uit het verleden bieden geen garantie voor de toekomst.' },
    { h:'4 · Regelgeving', p:'Vermelde financiële instrumenten kunnen onderworpen zijn aan vereisten van Euronext, FSMA, MiCA, het Belgische WVV, de Luxemburgse CSSF/AIFMD en de EU-prospectusverordening. Beschikbaarheid is beperkt tot in aanmerking komende beleggers.' },
    { h:'5 · Aansprakelijkheid & toepasselijk recht', p:'Voor zover wettelijk toegestaan aanvaardt Van Beirs Holding B.V. geen aansprakelijkheid voor het vertrouwen op deze website. Deze voorwaarden worden beheerst door het Belgische recht; geschillen vallen onder de rechtbanken van Antwerpen.' },
  ],
};

window.CONTENT.fr = {
  stat_brands:'Marques d’investissement', stat_target:'Objectif de portefeuille', stat_irr:'TRI cible moyen', stat_years:'Ans de M&A',
  about_p1:"Van Beirs Ventures B.V. est la société professionnelle de gestion d’investissement et de produits financiers du groupe Van Beirs, opérant sous Van Beirs Holding B.V.",
  about_p2:"L’entité supervise six véhicules d’investissement, structure et émet les instruments financiers du groupe, et gère l’intégration entre les marchés de capitaux et les portefeuilles de marques sous-jacents.",
  about_mandate:"Les activités du groupe sont centrées sur le capital d’investissement dans le luxe, la technologie et l’immobilier — et leurs combinaisons.",
  history_note:'Les dates patrimoniales concernent les marques du portefeuille. Les jalons du groupe restent à confirmer.',
  histItems:[
    { y:'1840', h:'Charles Fontana & Cie', d:'Maison de haute joaillerie fondée au 10, place Vendôme, Paris — aujourd’hui une maison patrimoniale du portefeuille.' },
    { y:'1897', h:'MINERVA', d:'Marque automobile belge ultra-luxe créée — à l’origine du programme de SUV à hydrogène assemblé à la main du groupe.' },
    { y:'2026', h:'Programme investisseurs du groupe', d:'Van Beirs Ventures publie son Group Investor Overview et lance les instruments financiers de la Phase I via les véhicules d’investissement.' },
  ],
  instr_meta:'Règl. Prospectus UE · FSMA',
  instrItems:[
    { h:'Obligation de placement privé', items:['Collateral Debt Obligations — placement privé','Coupon 9,0% p.a. · paiements trimestriels','Échéance 5 ans · remboursement in fine','Convertible avec droits en actions de classe B','Garantie sur les actifs de marque et de PI du groupe'] },
    { h:'Instruments financiers publics', items:['Euronext Bruxelles / obligations paneuropéennes','Conformité prospectus régulée par la FSMA','Obligation publique I — relais année 4','Obligation publique II — croissance année 5','Euro MTF · Bourse de Luxembourg'] },
    { h:'Instruments tokenisés', items:['Versions digital-native de tous les produits','Propriété et transfert enregistrés sur blockchain','Accès fractionné, tickets plus petits','Coupon et conversion par contrats intelligents','Architecture conforme à MiCA (UE)'] },
    { h:'VB Certus Capital SA', items:['SICAV-RAIF luxembourgeoise · multi-stratégie','Classes A · M · B · R','Supervision AIFM · loi Part II UCI','Rendement cible : 10–15% TRI','Cotation Euronext Bruxelles à 100M€+ d’encours'] },
  ],
  inv_meta:'Cantonné · par véhicule', inv_k1:'1er invest.', inv_k2:'Sortie 5 ans', inv_tbc:'À confirmer', inv_req:'Sur demande',
  portfolio:[
    { sc:'Innovations énergétiques', desc:'Stockage par batterie, intégration PV, recharge VE et systèmes hydrogène. Armoire HydraCell propriétaire.' },
    { sc:'Haute joaillerie', desc:'10, place Vendôme. Moins de 25 pièces uniques par an à partir d’1,5M€.' },
    { sc:'Automobile ultra-luxe', desc:'SUV hybride belge H2 V12. 100 unités/an, assemblé à la main à l’atelier d’Anvers.' },
    { sc:'Appareil IA souverain', desc:'Smartphone IA de luxe belge. Modèle européen, confidentialité sur l’appareil, aucune dépendance au cloud.' },
    { sc:'Field-to-fork', desc:'Connectivité directe field-to-fork, technologie de traçabilité et infrastructure de marché durable.' },
    { sc:'Défense · drone', desc:'UAS tactique OTAN. IA neuromorphique IMEC, supercondensateur graphène. EDF 2026 · Défense belge.' },
    { sc:'FinTech · Canton Network', desc:'Plateforme institutionnelle de security tokens sur le Canton Network — tokenise et règle les instruments financiers du groupe.' },
    { sc:'Résidences de marque', desc:'Résidences de marque ultra-luxe étendant la marque MINERVA à l’immobilier patrimonial de prestige.' },
    { sc:'Immobilier prime · Anvers', desc:'VB001 — hôtel de maître de 800m², Justitiestraat. Trois des quatre lots pré-signés. Classe R via VB Certus Capital.' },
  ],
  pitch_eyebrow:'Pour les entreprises en recherche de financement',
  pitch_company:'Informations sur la société', pitch_management:'Informations sur la direction', pitch_documents:'Documents', pitch_ask:'La demande',
  f_company:'Nom de la société', f_website:'Site web', f_country:'Pays', f_sector:'Secteur',
  f_contact:'Nom du contact', f_role:'Fonction', f_emailL:'E-mail', f_phone:'Téléphone',
  f_accounts:'Comptes des 3 dernières années', f_accounts_h:'PDF / XLSX — chiffres annuels', f_presentation:'Présentation de la société', f_presentation_h:'PDF — 10 diapositives max.',
  f_financing:'Financement requis (€)', f_timeframe:'Horizon',
  tf_select:'Choisir…', tf_now:'Immédiat (< 3 mois)', tf_3_6:'3–6 mois', tf_6_12:'6–12 mois', tf_exp:'Exploratoire',
  consent_pre:'Je consens à être contacté par e-mail concernant cette proposition, conformément à la ', consent_post:'.',
  pitch_submit:'Soumettre la proposition', pitch_redirect:'Redirection vers la page d’accueil…', file_choose:'Choisir un fichier', file_replace:'Remplacer le fichier',
  login_email_ph:'nom@institution.com',
  ft_rights:'Tous droits réservés',
  langLabel:'Langue', legal_eyebrow:'Mentions légales', legal_entityLine:'Van Beirs Holding B.V. · Anvers, Belgique', legal_dp:'Juridique & protection des données :', legal_updated:'Dernière mise à jour 2026.',
  privacySections:[
    { h:'1 · Responsable du traitement', p:'Ce site est exploité par Van Beirs Holding B.V. (Anvers, Belgique), agissant en qualité de responsable du traitement des données personnelles traitées par son intermédiaire.' },
    { h:'2 · Données traitées', p:'Les informations que vous transmettez (p. ex. nom, e-mail institutionnel, messages), les données d’authentification pour l’espace investisseurs, et les données techniques telles que l’adresse IP et le type de navigateur collectées via des cookies strictement nécessaires et optionnels.' },
    { h:'3 · Finalités & base légale', p:'Pour exploiter le site et l’espace investisseurs, répondre aux demandes et propositions, respecter les obligations légales et réglementaires, et — avec votre consentement — comprendre l’usage du site. Le traitement repose sur le consentement, l’intérêt légitime et l’obligation légale au titre du RGPD (Règlement (UE) 2016/679).' },
    { h:'4 · Cookies', p:'Les cookies strictement nécessaires assurent le fonctionnement du site et mémorisent votre langue. Les cookies d’analyse optionnels ne sont déposés qu’après consentement et peuvent être retirés à tout moment via « Paramètres des cookies ».' },
    { h:'5 · Conservation & destinataires', p:'Les données ne sont conservées que le temps nécessaire aux finalités ci-dessus ou requis par la loi, et partagées uniquement avec des prestataires et conseillers tenus à la confidentialité.' },
    { h:'6 · Vos droits', p:'Vous pouvez demander l’accès, la rectification, l’effacement, la limitation, la portabilité ou vous opposer au traitement, et introduire une réclamation auprès de l’Autorité de protection des données belge.' },
  ],
  termsSections:[
    { h:'1 · Absence d’offre ou de sollicitation', p:'Les informations de ce site sont fournies à titre d’information générale uniquement et ne constituent pas une offre, une sollicitation ou une recommandation de souscrire, d’acheter ou de vendre un instrument financier dans une quelconque juridiction.' },
    { h:'2 · Confidentialité', p:'Les documents accessibles via l’espace investisseurs sont confidentiels et destinés aux seuls destinataires autorisés. Ils ne peuvent être reproduits ou distribués sans accord écrit préalable.' },
    { h:'3 · Déclarations prospectives', p:'Les objectifs, projections, TRI ou multiples sont illustratifs, soumis à un risque important et ne constituent ni une prévision ni une garantie de performance future. Les performances passées ne préjugent pas des performances futures.' },
    { h:'4 · Réglementation', p:'Les instruments financiers mentionnés peuvent être soumis aux exigences d’Euronext, de la FSMA, de MiCA, du WVV belge, de la CSSF/AIFMD luxembourgeoise et du Règlement Prospectus de l’UE. La disponibilité est réservée aux investisseurs éligibles.' },
    { h:'5 · Responsabilité & droit applicable', p:'Dans les limites permises par la loi, Van Beirs Holding B.V. décline toute responsabilité en cas de recours à ce site. Les présentes conditions sont régies par le droit belge ; les litiges relèvent des tribunaux d’Anvers.' },
  ],
};
