/* Van Beirs — content localisation: Chinese & Japanese */
window.CONTENT.zh = {
  stat_brands:'投资品牌', stat_target:'投资组合目标', stat_irr:'平均目标内部收益率', stat_years:'并购经验（年）',
  about_p1:'Van Beirs Ventures B.V. 是 Van Beirs 集团旗下的专业投资管理与金融产品公司，隶属于 Van Beirs Holding B.V.。',
  about_p2:'该实体管理六个投资载体，构建并发行集团的金融工具，并负责协调资本市场与底层品牌组合之间的整合。',
  about_mandate:'集团的活动聚焦于奢侈品、科技与房地产领域的投资资本，以及上述领域的组合。',
  history_note:'',
  histItems:[
    { y:'1840', h:'Charles Fontana & Cie', d:'高级珠宝世家，创立于巴黎旺多姆广场10号——如今是投资组合中的传承品牌。' },
    { y:'1897', h:'MINERVA', d:'比利时超豪华汽车品牌成立——集团手工组装氢能SUV项目的基础。' },
    { y:'2026', h:'集团投资者计划', d:'Van Beirs Ventures 发布其 Group Investor Overview，并通过各投资载体启动第一阶段金融工具。' },
  ],
  instr_meta:'欧盟招股说明书条例 · FSMA',
  instrItems:[
    { h:'私募债券', items:['Collateral Debt Obligations — 私募发行','年息9.0% · 按季支付','5年期 · 到期一次性还本','可转换为B类股权','以集团品牌及知识产权资产作担保'] },
    { h:'公开金融工具', items:['布鲁塞尔泛欧交易所 / 泛欧债券','受 FSMA 监管的招股说明书合规','公开债券 I — 第4年过桥','公开债券 II — 第5年增长','Euro MTF · 卢森堡证券交易所'] },
    { h:'代币化工具', items:['所有产品的数字原生版本','基于区块链登记的所有权与转让','可分割认购，门槛更低','通过智能合约执行付息与转换','符合欧盟 MiCA 架构'] },
    { h:'VB Certus Capital SA', items:['卢森堡 SICAV-RAIF · 多策略','A · M · B · R 类','AIFM 监管 · Part II UCI 法','目标回报：10–15% 内部收益率','资产管理规模达1亿欧元以上于泛欧交易所上市'] },
  ],
  inv_meta:'独立隔离 · 按载体', inv_k1:'首次投资', inv_k2:'5年退出', inv_tbc:'待定', inv_req:'应要求提供',
  portfolio:[
    { sc:'能源创新', desc:'电池储能、光伏整合、电动车充电与氢能系统。自有 HydraCell 机柜。' },
    { sc:'高级珠宝', desc:'旺多姆广场10号。每年不足25件独一无二的作品，起价150万欧元。' },
    { sc:'超豪华汽车', desc:'比利时 H2 V12 混合动力SUV。年产100辆，于安特卫普工坊手工组装。' },
    { sc:'主权AI设备', desc:'比利时奢侈AI智能手机。欧洲模型，设备端隐私，零云端依赖。' },
    { sc:'从田间到餐桌', desc:'直接的从田间到餐桌互联、可追溯技术与可持续市场基础设施。' },
    { sc:'国防 · 无人机', desc:'北约战术无人机系统。IMEC 神经形态AI、石墨烯超级电容。EDF 2026 · 比利时国防部。' },
    { sc:'金融科技 · Canton Network', desc:'基于 Canton Network 的机构级证券型代币平台——对集团金融工具进行代币化与结算。' },
    { sc:'品牌住宅', desc:'超豪华品牌住宅，将 MINERVA 品牌延伸至顶级传承房地产。' },
    { sc:'优质房地产 · 安特卫普', desc:'VB001 — 位于 Justitiestraat 的800平方米联排豪宅。四套单元中三套已预签。经 VB Certus Capital 的 R 类。' },
  ],
  pitch_eyebrow:'致寻求投资的企业',
  pitch_company:'公司信息', pitch_management:'管理层信息', pitch_documents:'文件', pitch_ask:'融资需求',
  f_company:'公司名称', f_website:'网站', f_country:'国家', f_sector:'行业',
  f_contact:'联系人姓名', f_role:'职位', f_emailL:'电子邮箱', f_phone:'电话',
  f_accounts:'近3年财务报表', f_accounts_h:'PDF / XLSX — 年度数据', f_presentation:'公司介绍', f_presentation_h:'PDF — 最多10页',
  f_financing:'所需融资额（€）', f_timeframe:'时间框架',
  tf_select:'请选择…', tf_now:'立即（< 3个月）', tf_3_6:'3–6个月', tf_6_12:'6–12个月', tf_exp:'初步探讨',
  consent_pre:'我同意就本提案通过电子邮件与我联系，并符合', consent_post:'。',
  pitch_submit:'提交提案', pitch_redirect:'正在返回首页…', file_choose:'选择文件', file_replace:'更换文件',
  login_email_ph:'name@institution.com',
  ft_rights:'版权所有',
  langLabel:'语言', legal_eyebrow:'法律', legal_entityLine:'Van Beirs Holding B.V. · 比利时安特卫普', legal_dp:'法律与数据保护：', legal_updated:'最后更新于2026年。',
  privacySections:[
    { h:'1 · 数据控制者', p:'本网站由 Van Beirs Holding B.V.（比利时安特卫普）运营，作为通过本网站处理的个人数据的数据控制者。' },
    { h:'2 · 我们处理的数据', p:'您提交的信息（如姓名、机构邮箱、留言）、投资者登录的认证数据，以及通过严格必要和可选 Cookie 收集的技术数据（如IP地址和浏览器类型）。' },
    { h:'3 · 目的与法律依据', p:'用于运营网站及投资者专区、回应咨询与提案、履行法律与监管义务，并在征得您同意后了解网站使用情况。处理依据为同意、合法利益及 GDPR（欧盟2016/679号条例）下的法律义务。' },
    { h:'4 · Cookie', p:'严格必要的 Cookie 维持网站运行并保存您的语言偏好。可选分析 Cookie 仅在同意后设置，并可随时通过"Cookie 设置"撤回。' },
    { h:'5 · 保留与接收方', p:'数据仅在上述目的所需或法律要求的期限内保留，并仅与受保密义务约束的服务提供商和顾问共享。' },
    { h:'6 · 您的权利', p:'您可要求访问、更正、删除、限制、可携带或反对处理，并可向比利时数据保护局提出投诉。' },
  ],
  termsSections:[
    { h:'1 · 非要约或招揽', p:'本网站信息仅供一般参考，不构成在任何司法管辖区认购、购买或出售任何金融工具的要约、招揽或建议。' },
    { h:'2 · 保密', p:'通过投资者专区可访问的材料属保密性质，仅供获授权的接收方使用。未经事先书面同意，不得复制或分发。' },
    { h:'3 · 前瞻性陈述', p:'任何目标、预测、内部收益率或倍数均为示例性质，存在重大风险，并非对未来业绩的预测或保证。过往业绩不代表未来表现。' },
    { h:'4 · 监管', p:'所述金融工具可能受 Euronext、FSMA、MiCA、比利时 WVV、卢森堡 CSSF/AIFMD 及欧盟招股说明书条例的要求约束。仅向合资格投资者提供。' },
    { h:'5 · 责任与适用法律', p:'在法律允许的范围内，Van Beirs Holding B.V. 对依赖本网站不承担任何责任。本条款受比利时法律管辖；争议由安特卫普法院管辖。' },
  ],
};

window.CONTENT.ja = {
  stat_brands:'投資ブランド', stat_target:'ポートフォリオ目標', stat_irr:'平均目標IRR', stat_years:'M&A経験（年）',
  about_p1:'Van Beirs Ventures B.V. は、Van Beirs グループのプロフェッショナルな投資運用・金融商品会社であり、Van Beirs Holding B.V. のもとで事業を行っています。',
  about_p2:'当エンティティは6つの投資ビークルを統括し、グループの金融商品を組成・発行するとともに、資本市場と傘下のブランドポートフォリオの統合を管理します。',
  about_mandate:'グループの活動は、ラグジュアリー・テクノロジー・不動産およびそれらの組み合わせへの投資資本に重点を置いています。',
  history_note:'',
  histItems:[
    { y:'1840', h:'Charles Fontana & Cie', d:'パリ・ヴァンドーム広場10番地に創業したオートジョアイヨリーのメゾン——現在はポートフォリオ内のヘリテージメゾン。' },
    { y:'1897', h:'MINERVA', d:'ベルギーの超高級自動車ブランドを創設——グループの手組み水素SUVプログラムの基盤。' },
    { y:'2026', h:'グループ投資家プログラム', d:'Van Beirs Ventures は Group Investor Overview を公表し、各投資ビークルを通じてフェーズIの金融商品を立ち上げます。' },
  ],
  instr_meta:'EU目論見書規則 · FSMA',
  instrItems:[
    { h:'私募債', items:['Collateral Debt Obligations — 私募発行','年率9.0%クーポン · 四半期払い','5年満期 · 一括償還','クラスB株式権付き転換可能','グループのブランド・知財資産を担保'] },
    { h:'公募金融商品', items:['ユーロネクスト・ブリュッセル / 汎欧州債','FSMA規制の目論見書コンプライアンス','公募債I — 4年目ブリッジ','公募債II — 5年目グロース','Euro MTF · ルクセンブルク証券取引所'] },
    { h:'トークン化商品', items:['全商品のデジタルネイティブ版','ブロックチェーン登録による所有・移転','小口での分割アクセス','スマートコントラクトによるクーポン・転換','EU MiCA準拠アーキテクチャ'] },
    { h:'VB Certus Capital SA', items:['ルクセンブルクSICAV-RAIF · マルチストラテジー','クラス A · M · B · R','AIFM監督 · Part II UCI法','目標リターン：10–15% IRR','運用資産1億ユーロ超でユーロネクスト・ブリュッセル上場'] },
  ],
  inv_meta:'リングフェンス · ビークル別', inv_k1:'初回投資', inv_k2:'5年エグジット', inv_tbc:'未定', inv_req:'お問い合わせ',
  portfolio:[
    { sc:'エネルギー革新', desc:'蓄電池、PV統合、EV充電、水素システム。独自のHydraCellキャビネット。' },
    { sc:'オートジョアイヨリー', desc:'ヴァンドーム広場10番地。年間25点未満の唯一無二の作品、150万ユーロから。' },
    { sc:'超高級自動車', desc:'ベルギー製H2 V12ハイブリッドSUV。年産100台、アントワープのアトリエで手組み。' },
    { sc:'ソブリンAIデバイス', desc:'ベルギーのラグジュアリーAIスマートフォン。欧州モデル、オンデバイスのプライバシー、クラウド非依存。' },
    { sc:'フィールド・トゥ・フォーク', desc:'直接的なフィールド・トゥ・フォーク接続、トレーサビリティ技術、持続可能な市場インフラ。' },
    { sc:'防衛 · ドローン', desc:'NATO戦術UAS。IMECニューロモルフィックAI、グラフェンスーパーキャパシタ。EDF 2026 · ベルギー国防省。' },
    { sc:'フィンテック · Canton Network', desc:'Canton Network上の機関投資家向けセキュリティトークン基盤——グループの金融商品をトークン化・決済。' },
    { sc:'ブランドレジデンス', desc:'MINERVAブランドをプライムなヘリテージ不動産へ拡張する超高級ブランドレジデンス。' },
    { sc:'プライム不動産 · アントワープ', desc:'VB001 — Justitiestraatの800㎡タウンハウス。4区画中3区画が事前契約済み。VB Certus Capital経由のクラスR。' },
  ],
  pitch_eyebrow:'投資をお探しの企業の皆さまへ',
  pitch_company:'会社情報', pitch_management:'経営陣情報', pitch_documents:'書類', pitch_ask:'資金ニーズ',
  f_company:'会社名', f_website:'ウェブサイト', f_country:'国', f_sector:'業種',
  f_contact:'担当者名', f_role:'役職', f_emailL:'メールアドレス', f_phone:'電話',
  f_accounts:'直近3年分の決算書', f_accounts_h:'PDF / XLSX — 年次数値', f_presentation:'会社プレゼンテーション', f_presentation_h:'PDF — 最大10枚',
  f_financing:'必要資金額（€）', f_timeframe:'時期',
  tf_select:'選択…', tf_now:'即時（3か月未満）', tf_3_6:'3〜6か月', tf_6_12:'6〜12か月', tf_exp:'検討段階',
  consent_pre:'本提案に関してメールで連絡を受けることに、', consent_post:'に従って同意します。',
  pitch_submit:'提案を送信', pitch_redirect:'ホームページに戻っています…', file_choose:'ファイルを選択', file_replace:'ファイルを変更',
  login_email_ph:'name@institution.com',
  ft_rights:'All rights reserved',
  langLabel:'言語', legal_eyebrow:'法務', legal_entityLine:'Van Beirs Holding B.V. · ベルギー・アントワープ', legal_dp:'法務・データ保護：', legal_updated:'最終更新 2026年。',
  privacySections:[
    { h:'1 · データ管理者', p:'本ウェブサイトは Van Beirs Holding B.V.（ベルギー・アントワープ）が運営し、本サイトを通じて処理される個人データの管理者として行動します。' },
    { h:'2 · 取得するデータ', p:'お客様が送信される情報（氏名、法人メール、メッセージ等）、投資家ログインの認証データ、ならびに必須および任意のCookieを通じて収集されるIPアドレスやブラウザ種別などの技術データ。' },
    { h:'3 · 目的と法的根拠', p:'サイトおよび投資家エリアの運営、問い合わせや提案への対応、法令・規制上の義務の履行、ならびに同意に基づくサイト利用状況の把握のため。処理はGDPR（規則(EU)2016/679）に基づく同意・正当な利益・法的義務に依拠します。' },
    { h:'4 · Cookie', p:'必須Cookieはサイトの動作と言語設定を維持します。任意の分析Cookieは同意後にのみ設定され、「Cookie設定」からいつでも撤回できます。' },
    { h:'5 · 保管と提供先', p:'データは上記目的に必要な期間または法令で要求される期間に限り保管し、守秘義務を負うサービス提供者および助言者にのみ共有します。' },
    { h:'6 · お客様の権利', p:'アクセス、訂正、消去、制限、ポータビリティの請求または処理への異議を申し立てることができ、ベルギーのデータ保護当局に苦情を申し立てることができます。' },
  ],
  termsSections:[
    { h:'1 · 勧誘・申込ではないこと', p:'本サイトの情報は一般的な情報提供のみを目的とし、いかなる法域においても金融商品の申込・勧誘・購入・売却の推奨を構成するものではありません。' },
    { h:'2 · 機密保持', p:'投資家エリアを通じてアクセスできる資料は機密であり、認可された受領者のみを対象とします。事前の書面による同意なく複製または配布することはできません。' },
    { h:'3 · 将来予想に関する記述', p:'目標、予測、IRRや倍率の数値は例示であり、重大なリスクを伴い、将来の成果の予測や保証ではありません。過去の実績は将来の成果を示すものではありません。' },
    { h:'4 · 規制', p:'記載の金融商品は、Euronext、FSMA、MiCA、ベルギーWVV、ルクセンブルクCSSF/AIFMD、EU目論見書規則の要件の対象となる場合があります。提供は適格投資家に限定されます。' },
    { h:'5 · 責任と準拠法', p:'法律で認められる範囲において、Van Beirs Holding B.V. は本サイトへの依拠について一切の責任を負いません。本規約はベルギー法に準拠し、紛争はアントワープの裁判所の管轄に服します。' },
  ],
};
