/* Van Beirs — full content localisation (window.CONTENT). Merged over I18N in app.jsx.
   Brand names, currency figures and regulator names are kept untranslated by design. */
window.CONTENT = {
  en: {
    stat_brands:'Investment brands', stat_target:'Portfolio target', stat_irr:'Avg. target IRR', stat_years:'Years M&A',
    about_p1:"Van Beirs Ventures B.V. is the professional investment management and financial products company of the Van Beirs group, operating under Van Beirs Holding B.V.",
    about_p2:"The entity oversees six investment vehicles, structures and issues the group's financial instruments, and manages the integration between capital markets and the underlying brand portfolios.",
    about_mandate:"The group's activities are centred on investment capital across luxury, technology and real estate — and combinations thereof.",
    history_note:'Heritage dates reflect portfolio brands. Group corporate milestones to be confirmed.',
    histItems:[
      { y:'1840', h:'Charles Fontana & Cie', d:'House of haute joaillerie founded at 10, Place Vendôme, Paris — today a heritage maison within the portfolio.' },
      { y:'1897', h:'MINERVA', d:'Belgian ultra-luxury automotive marque established — the basis of the group’s hand-assembled hydrogen SUV programme.' },
      { y:'2026', h:'Group Investor Programme', d:'Van Beirs Ventures publishes its Group Investor Overview and launches Phase I financial instruments across the investment vehicles.' },
    ],
    instr_meta:'EU Prospectus Reg. · FSMA',
    instrItems:[
      { h:'Private Placement Bond', items:['Collateral Debt Obligations — private placement','9.0% p.a. coupon · quarterly payments','5-year tenor · bullet repayment','Convertible with Class B equity rights','Secured against group brand & IP assets'] },
      { h:'Public Financial Instruments', items:['Euronext Brussels / pan-European bonds','FSMA-regulated prospectus compliance','Public Bond I — Year 4 bridge','Public Bond II — Year 5 growth','Euro MTF · Luxembourg Stock Exchange'] },
      { h:'Tokenized Instruments', items:['Digital-native versions of all products','Blockchain-registered ownership & transfer','Fractionalised access, smaller tickets','Smart-contract coupon & conversion','EU MiCA-compliant architecture'] },
      { h:'VB Certus Capital SA', items:['Luxembourg SICAV-RAIF · multi-strategy','Classes A · M · B · R','AIFM supervised · Part II UCI law','Target return: 10–15% IRR','Euronext Brussels listing at € 100M+ AUM'] },
    ],
    inv_meta:'Ring-fenced · per-vehicle', inv_k1:'1st invest.', inv_k2:'5-yr exit', inv_tbc:'TBC', inv_req:'On request',
    portfolio:[
      { sc:'Energy Innovations', desc:'Battery storage, PV integration, EV charging & hydrogen systems. Proprietary HydraCell cabinet.' },
      { sc:'Haute Joaillerie', desc:'10, Place Vendôme. Fewer than 25 unique pieces per year from €1.5M.' },
      { sc:'Ultra-Luxury Automotive', desc:'Belgian H2 V12 hybrid SUV. 100 units/yr, hand-assembled in the Antwerp atelier.' },
      { sc:'AI Sovereign Device', desc:'Belgian luxury AI smartphone. European model, on-device privacy, zero cloud dependency.' },
      { sc:'Field-to-Fork', desc:'Direct field-to-fork connectivity, traceability technology and sustainable market infrastructure.' },
      { sc:'Defence · Drone', desc:'NATO tactical UAS. IMEC neuromorphic AI, graphene supercapacitor. EDF 2026 · Belgian MoD.' },
      { sc:'FinTech · Canton Network', desc:'Institutional security-token platform on the Canton Network — tokenises and settles the group’s financial instruments.' },
      { sc:'Branded Residences', desc:'Ultra-luxury branded residences extending the MINERVA marque into prime patrimony real estate.' },
      { sc:'Prime RE · Antwerp', desc:'VB001 — 800m² Justitiestraat herenhuis. Three of four units pre-signed. Class R via VB Certus Capital.' },
    ],
    pitch_eyebrow:'For companies seeking investment',
    pitch_company:'Company information', pitch_management:'Management information', pitch_documents:'Documents', pitch_ask:'The ask',
    f_company:'Company name', f_website:'Website', f_country:'Country', f_sector:'Sector',
    f_contact:'Contact name', f_role:'Role', f_emailL:'Email', f_phone:'Phone',
    f_accounts:"Last 3 years' accounts", f_accounts_h:'PDF / XLSX — annual figures', f_presentation:'Company presentation', f_presentation_h:'PDF — max 10 slides',
    f_financing:'Financing required (€)', f_timeframe:'Timeframe',
    tf_select:'Select…', tf_now:'Immediate (< 3 months)', tf_3_6:'3–6 months', tf_6_12:'6–12 months', tf_exp:'Exploratory',
    consent_pre:'I consent to be contacted by email regarding this proposal, in accordance with the ', consent_post:'.',
    pitch_submit:'Submit proposal', pitch_redirect:'Redirecting to the home page…', file_choose:'Choose file', file_replace:'Replace file',
    login_email_ph:'name@institution.com',
    ft_rights:'All rights reserved',
    langLabel:'Language', legal_eyebrow:'Legal', legal_entityLine:'Van Beirs Holding B.V. · Antwerp, Belgium', legal_dp:'Legal & data protection:', legal_updated:'Last updated 2026.',
    privacySections:[
      { h:'1 · Data controller', p:'This website is operated by Van Beirs Holding B.V. (Antwerp, Belgium), acting as data controller for the personal data processed through it.' },
      { h:'2 · Data we process', p:'Information you submit (e.g. name, institutional email, messages), authentication data for the investor login, and technical data such as IP address and browser type collected via strictly necessary and optional cookies.' },
      { h:'3 · Purposes & legal basis', p:'To operate the site and investor area, respond to enquiries and proposals, meet legal and regulatory obligations, and — with your consent — to understand site usage. Processing relies on consent, legitimate interest, and legal obligation under the GDPR (Regulation (EU) 2016/679).' },
      { h:'4 · Cookies', p:'Strictly necessary cookies keep the site functioning and your language preference. Optional analytics cookies are set only after consent and can be withdrawn at any time via “Cookie settings”.' },
      { h:'5 · Retention & recipients', p:'Data is retained only as long as necessary for the purposes above or as required by law, and shared solely with service providers and advisers bound by confidentiality.' },
      { h:'6 · Your rights', p:'You may request access, rectification, erasure, restriction, portability, or object to processing, and lodge a complaint with the Belgian Data Protection Authority.' },
    ],
    termsSections:[
      { h:'1 · No offer or solicitation', p:'The information on this website is provided for general information only and does not constitute an offer, solicitation, or recommendation to subscribe for, purchase, or sell any financial instrument in any jurisdiction.' },
      { h:'2 · Confidentiality', p:'Materials accessible through the investor area are confidential and intended for authorised recipients only. They may not be reproduced or distributed without prior written consent.' },
      { h:'3 · Forward-looking statements', p:'Any targets, projections, IRR or multiple figures are illustrative, subject to significant risk, and not a forecast or guarantee of future performance. Past performance is not indicative of future results.' },
      { h:'4 · Regulatory', p:'Financial instruments referenced may be subject to Euronext, FSMA, MiCA, Belgian WVV, Luxembourg CSSF/AIFMD and EU Prospectus Regulation requirements. Availability is restricted to eligible investors.' },
      { h:'5 · Liability & governing law', p:'To the extent permitted by law, Van Beirs Holding B.V. accepts no liability for reliance on this website. These terms are governed by Belgian law; disputes fall under the courts of Antwerp.' },
    ],
  },
};
